version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1
jobs:
  build:
    environment:
        CHROME_BIN: "/usr/bin/google-chrome"
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # - run: npm test
            - run: npm run-script build --prod
  aws-s3:
    docker:
      - image: cimg/python:3.6
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: ls -lrt
      - deploy:
          name: List S3 bucket contents
          command: |
            aws s3 ls s3://ganesha-serverless/

workflows:
    build:
      jobs:
        - build
        - aws-s3:
            requires: 
              - build
            context: aws_s3_write
