version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1
jobs:
  build:
    environment:
        CHROME_BIN: "/usr/bin/google-chrome"
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # - run: npm test
            - run: npm run-script build-prod
      - persist_to_workspace:
          root: dist
          paths:
            -  .
  aws-s3:
    docker:
      - image: cimg/python:3.6
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - deploy:
          name: Upload to S3 bucket1
          command: |
            aws s3 ls s3://ganesha-serverless/dev/
            aws s3 rm s3://ganesha-serverless/dev/ --recursive
            aws s3 cp angular-test s3://ganesha-serverless/dev/ --recursive --sse --storage-class ONEZONE_IA
            aws s3 ls s3://ganesha-serverless/dev/

workflows:
    build:
      jobs:
        - build
        - aws-s3:
            requires: 
              - build
            context: aws_s3_write
